import "./globals.css";
import { Body } from "./Body";

export const metadata = {
  description: "Generated by Next.js",
  title: "Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-mauvedark1">
      <Body>{children}</Body>
    </html>
  );
}
