import "./globals.css";
import { Body } from "./Body";

export const metadata = {
  description: "Generated by Next.js",
  title: "Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-mauvedark1">
      <head>
        <link rel="preconnect" href="https://rsms.me/" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </head>
      <Body>{children}</Body>
    </html>
  );
}
