import { twMerge } from "tailwind-merge";
import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  description: "Generated by Next.js",
  title: "Next.js",
};

const inter = Inter({
  display: "swap",
  preload: true,
  style: "normal",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-slatedark1">
      <body className={twMerge(inter.className, "")}>{children}</body>
    </html>
  );
}
