name: CI actions
run-name: CI actions (${{ github.actor }})
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: actions/checkout@v3
      - name: Use Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run tsc, eslint and tests
        uses: borales/actions-yarn@v4
        with:
          cmd: run-checks
