name: CI actions
run-name: CI actions (${{ github.actor }})
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout git
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun i
      - name: Install dependencies
        run: bun run test
      - name: eslint
        run: bun run lint
      - name: tsc
        run: bun run tsc
      - name: Build
        run: bun run build
